### ISSUE TITLE
Error in project setup

### ISSUE THREAD

**Issue by spandl** [googledatastudio/dscc-gen#38]
After having installed dscc-gen viz I am getting prompted with the project name.

However, when I insert the name of the dev bucket the setup returns an error.

I made however sure that `gs://dscc-test/testViz` is a valid address, I can download a file from this bucket (manifest.json)

```
MacBook-Pro-2:Data Studio Community Component  ralph$ npx @google/dscc-gen viz
npx: installed 342 in 13.913s
? Project name testViz
? What is your dev bucket? gs://dscc-test/testViz(node:78492) 
```

**Error Message**
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at InputPrompt.onError (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/inquirer/lib/prompts/input.js:95:35)
    at SafeSubscriber._next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Observable.js:66:21)
    at SafeSubscriber.__tryOrUnsub (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeUntilSubscriber.Subscriber._next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:89:26)
    at TakeUntilSubscriber.Subscriber.next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:66:18)
    at FilterSubscriber._next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/operators/filter.js:52:30)
    at FilterSubscriber.Subscriber.next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:66:18)
    at RefCountSubscriber.Subscriber._next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:89:26)
    at RefCountSubscriber.Subscriber.next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subject.js:60:25)
    at ConnectableSubscriber.Subscriber._next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:89:26)
    at ConnectableSubscriber.Subscriber.next (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/ralph/.npm/_npx/78492/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
(node:78492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:78492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by y3l2n** [comment]
Quick debug question: what is the `(node:78492) ` at the end of your bucket name?

**Comment by spandl** [comment]
I think it is just a missing line jump

Before enter
![image](https://user-images.githubusercontent.com/5740594/61504243-b226d500-a9a8-11e9-9079-c4eb8e6a2432.png)

After Enter
![image](https://user-images.githubusercontent.com/5740594/61504252-b6eb8900-a9a8-11e9-95b9-9b43ed326818.png)

**Comment by y3l2n** [comment]
What is the output of:

`npx @google/dscc-gen -v`

Also -

Does it work if you do:

`npx --ignore-existing @google/dscc-gen viz` ?

**Comment by spandl** [comment]
> npx @google/dscc-gen -v

npx: installed 342 in 15.354s
2.0.17

> npx --ignore-existing @google/dscc-gen viz

```
(node:91771) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at InputPrompt.onError (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/inquirer/lib/prompts/input.js:95:35)
    at SafeSubscriber._next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Observable.js:66:21)
    at SafeSubscriber.__tryOrUnsub (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeUntilSubscriber.Subscriber._next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:89:26)
    at TakeUntilSubscriber.Subscriber.next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:66:18)
    at FilterSubscriber._next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/operators/filter.js:52:30)
    at FilterSubscriber.Subscriber.next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:66:18)
    at RefCountSubscriber.Subscriber._next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:89:26)
    at RefCountSubscriber.Subscriber.next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subject.js:60:25)
    at ConnectableSubscriber.Subscriber._next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:89:26)
    at ConnectableSubscriber.Subscriber.next (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/ralph/.npm/_npx/91771/lib/node_modules/@google/dscc-gen/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
(node:91771) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:91771) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by y3l2n** [comment]
I'm able to reproduce this on a Macbook, but the error doesn't stop me from continuing. I'll keep looking into the exception, but you should be able to answer the next question, press "return", and continue on workflow.

**Comment by spandl** [comment]
OK, that is at least one step forward.

However, I can't get to the next question, when pressing enter. 
Also, if I go a step back (same question is asked again) and I press return, nothing happens.

I have to Ctrl-C to get out

**Comment by y3l2n** [comment]
Once the error message finishes printing, press the up arrow key and it should re-prompt you with the prod bucket question. Fill that out, then press Enter. I know it's a workaround, but at least you'll have a working template at the end of this.

**Comment by spandl** [comment]
The up-arrow (or return key) works, but hitting then enter after the question is answered is not working here. Tried many keys to get going, all negative.

**Comment by albutko** [comment]
Experiencing the exact same error/issues with the specs listed below

OS: MacOS - Mojave 10.14.5
npm: 6.10.1
dscc-gen: 2.0.17

Reprompting the dev bucket input with &#8593;  and pressing Enter does nothing.

**Comment by y3l2n** [comment]
Are you still getting it (as of basically now)?

**Comment by albutko** [comment]
Nope! The error seems to be resolved. I was able to successfully run `npx @google/dscc-gen viz`

**Comment by spandl** [comment]
I have still the same issue. I even upgraded npm to the exact same specs as @albutko.
Same OS, same npm, same dscc-gen

I also created a new empty folder `gs://dscc-test/viz2` with no luck. Same error message.

**Comment by albutko** [comment]
**UPDATE:** I jumped the gun on calling it resolved. I ran successfully ran the command for one visualization, but on further attempts this error persists.

**Comment by y3l2n** [comment]
I made some updates and deployed a new version of the tool today. It's been working for the past few hours on my Macbook Pro. @albutko / @spandl  are you seeing the same errors as before?

**Comment by spandl** [comment]
Nope, sorry, still getting the exact same error. Tried with different folders again

It tells me -v `2.0.18`

**Comment by albutko** [comment]
Any updates on this? Still having this issue with version `2.0.19`

<img width="1208" alt="Screen Shot 2019-08-22 at 11 59 59 AM" src="https://user-images.githubusercontent.com/15615810/63530541-a9a84980-c4d4-11e9-8bfb-6793dbac37db.png">

After the warning is thrown I try to prompt the prod bucket question with the up arrow but the dev bucket question is reprompted.

**Comment by y3l2n** [comment]
What node/npm versions are y'all using?

**Comment by spandl** [comment]
npm -version
6.10.1

**Comment by spandl** [comment]
I am now actually getting a new error:
`>> Error: Command failed with exit code 1 (EPERM): gsutil acl get gs://dscv`

**Comment by y3l2n** [comment]
Can you try again? We made a *ton* of changes and I literally just redeployed.

**Comment by spandl** [comment]
```
MacBook-Pro-2:Data Studio Community Component  ralph$ npx @google/dscc-gen viz
npx: installed 347 in 11.039s
? Project name DSCV
? What is your dev bucket? gs://
>> Error: Command failed with exit code 1 (EPERM): gsutil acl get gs://dscv
```

I also tried
`npx --ignore-existing @google/dscc-gen viz`

Anything else I should try?

**Comment by y3l2n** [comment]
Does gsutil work for you outside of the tool?

**Comment by spandl** [comment]
I can do stuff like 
`gcloud projects list --format="json" \`

and do get a valid list back. Haven't tried anything else.

**Comment by spandl** [comment]
And I managed to upload a file as well.
`gsutil cp README.md  gs://dscv/`
`Operation completed over 1 objects/938.0 B. `

**Comment by clemlem** [comment]
I had the same issue. When you check how they validate permission in https://github.com/googledatastudio/tooling/blob/f00c65c9a85bb1c6ec6a9f9a012d73f3c03af61f/packages/dscc-gen/src/viz/validation.ts#L60, they use the cmd `gsutil acl get gs://<your bucket>` which produces a 400 error if your bucket has a uniform bucket-level access. Try creating your bucket with `gsutil mb -b off -l <your region> gs://<your bucket name>` and it should work

**Comment by kdfriedman** [comment]
This may be a trivial suggestion but have you tried running `gcloud auth login` before attempting to install `dscc-gen viz` ? I was encountering the same issue and realized I hadn't set proper authentication for accessing my buckets.

**Comment by kmclaugh** [comment]
> I had the same issue. When you check how they validate permission in
> 
> https://github.com/googledatastudio/tooling/blob/f00c65c9a85bb1c6ec6a9f9a012d73f3c03af61f/packages/dscc-gen/src/viz/validation.ts#L60
> 
> , they use the cmd `gsutil acl get gs://<your bucket>` which produces a 400 error if your bucket has a uniform bucket-level access. Try creating your bucket with `gsutil mb -b off -l <your region> gs://<your bucket name>` and it should work

Confirmed, this worked for me

**Comment by aschor** [comment]
> I had the same issue. When you check how they validate permission in
> 
> https://github.com/googledatastudio/tooling/blob/f00c65c9a85bb1c6ec6a9f9a012d73f3c03af61f/packages/dscc-gen/src/viz/validation.ts#L60
> 
> , they use the cmd `gsutil acl get gs://<your bucket>` which produces a 400 error if your bucket has a uniform bucket-level access. Try creating your bucket with `gsutil mb -b off -l <your region> gs://<your bucket name>` and it should work

Hi,

in my case, my organization REQUIRES buckets to be created with uniform bucket-level access. So I cannot create one without, there is an org constraint on that. 

So basically I'm stuck even before starting. whoops. does anyone have another option please ?
